// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaleProject.DataAccess;

#nullable disable

namespace SaleProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250728115442_initiald")]
    partial class initiald
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaleProject.Entities.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("SaleProject.Entities.CustomerContactInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerContactInfos");
                });

            modelBuilder.Entity("SaleProject.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SaleProject.Entities.PurchaseInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SupplierId")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierId1")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId1");

                    b.ToTable("PurchaseInvoices");
                });

            modelBuilder.Entity("SaleProject.Entities.PurchaseInvoiceProducts", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurchaseInvoiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductId1");

                    b.HasIndex("PurchaseInvoiceId");

                    b.ToTable("PurchaseInvoiceProductss");
                });

            modelBuilder.Entity("SaleProject.Entities.SaleInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerId1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId1");

                    b.ToTable("SaleInvoices");
                });

            modelBuilder.Entity("SaleProject.Entities.SaleInvoiceProducts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("SaleInvoiceId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductId1");

                    b.HasIndex("SaleInvoiceId");

                    b.ToTable("SaleInvoiceProductss");
                });

            modelBuilder.Entity("SaleProject.Entities.Store", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("SaleProject.Entities.StoreStock", b =>
                {
                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId1")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("StoreId", "ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("StoreStocks");
                });

            modelBuilder.Entity("SaleProject.Entities.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("SaleProject.Entities.SupplierContactInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId")
                        .IsUnique();

                    b.ToTable("SupplierContactInfos");
                });

            modelBuilder.Entity("SaleProject.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SaleProject.Entities.CustomerContactInfo", b =>
                {
                    b.HasOne("SaleProject.Entities.Customer", "Customer")
                        .WithOne("ContactInfo")
                        .HasForeignKey("SaleProject.Entities.CustomerContactInfo", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SaleProject.Entities.PurchaseInvoice", b =>
                {
                    b.HasOne("SaleProject.Entities.Supplier", "Supplier")
                        .WithMany("BuyInvoices")
                        .HasForeignKey("SupplierId1");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SaleProject.Entities.PurchaseInvoiceProducts", b =>
                {
                    b.HasOne("SaleProject.Entities.Product", "Product")
                        .WithMany("PurchaseInvoiceProductss")
                        .HasForeignKey("ProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleProject.Entities.PurchaseInvoice", "PurchaseInvoice")
                        .WithMany("PurchaseInvoiceProductss")
                        .HasForeignKey("PurchaseInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PurchaseInvoice");
                });

            modelBuilder.Entity("SaleProject.Entities.SaleInvoice", b =>
                {
                    b.HasOne("SaleProject.Entities.Customer", "Customer")
                        .WithMany("SaleInvoices")
                        .HasForeignKey("CustomerId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SaleProject.Entities.SaleInvoiceProducts", b =>
                {
                    b.HasOne("SaleProject.Entities.Product", "Product")
                        .WithMany("SaleInvoiceProductss")
                        .HasForeignKey("ProductId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaleProject.Entities.SaleInvoice", "SaleInvoice")
                        .WithMany("SaleInvoiceProductss")
                        .HasForeignKey("SaleInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SaleInvoice");
                });

            modelBuilder.Entity("SaleProject.Entities.StoreStock", b =>
                {
                    b.HasOne("SaleProject.Entities.Product", "Product")
                        .WithMany("StoreStocks")
                        .HasForeignKey("ProductId1");

                    b.HasOne("SaleProject.Entities.Store", "Store")
                        .WithMany("StoreStocks")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SaleProject.Entities.SupplierContactInfo", b =>
                {
                    b.HasOne("SaleProject.Entities.Supplier", "Supplier")
                        .WithOne("ContactInfo")
                        .HasForeignKey("SaleProject.Entities.SupplierContactInfo", "SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SaleProject.Entities.Customer", b =>
                {
                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("SaleInvoices");
                });

            modelBuilder.Entity("SaleProject.Entities.Product", b =>
                {
                    b.Navigation("PurchaseInvoiceProductss");

                    b.Navigation("SaleInvoiceProductss");

                    b.Navigation("StoreStocks");
                });

            modelBuilder.Entity("SaleProject.Entities.PurchaseInvoice", b =>
                {
                    b.Navigation("PurchaseInvoiceProductss");
                });

            modelBuilder.Entity("SaleProject.Entities.SaleInvoice", b =>
                {
                    b.Navigation("SaleInvoiceProductss");
                });

            modelBuilder.Entity("SaleProject.Entities.Store", b =>
                {
                    b.Navigation("StoreStocks");
                });

            modelBuilder.Entity("SaleProject.Entities.Supplier", b =>
                {
                    b.Navigation("BuyInvoices");

                    b.Navigation("ContactInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
